#!/usr/bin/env python3
"""Generate a sweep of broadcast .cm files for phase-one baseline
benchmarking.

For each (nodes, group_size) combination, emits one .cm containing a
single broadcast operation from group member[0] to the rest of the
group. The generator targets the fat-tree topology; nodes sizes should
be of the form K^3/4 (K even) for htsim's FatTreeTopology: 16 (K=4),
128 (K=8), 1024 (K=16).

Per the Hoefler benchmarking guidance, each (nodes, group_size) point
gets `--reps` independent matrices, each drawing a fresh random group
membership. The downstream runner treats each matrix as one rep so
variance in the plot reflects *workload* variance (where the group
lands in the topology), which is the source of variance that actually
matters under deterministic ECMP_FIB path selection.

Output layout:
    <out_dir>/bcast_n<NODES>_g<GROUP>_r<REP>.cm
    <out_dir>/manifest.txt        # one line: nodes group rep path

Invoke from the connection_matrices directory:
    python3 gen_bcast_sweep.py --out bcast_sweep --reps 10
"""

import argparse
import os
import random


def valid_fat_tree_sizes(max_nodes):
    """Return node counts of form K^3/4 up to max_nodes, even K >= 4."""
    out = []
    k = 4
    while True:
        n = (k ** 3) // 4
        if n > max_nodes:
            break
        out.append(n)
        k += 2
    return out


def choose_group(total_nodes, group_size, rng):
    """Pick group_size distinct node ids from [0, total_nodes)."""
    return sorted(rng.sample(range(total_nodes), group_size))


def write_cm(path, nodes, group, payload_bytes):
    """Write a .cm with a single broadcast from group[0] to the rest."""
    with open(path, "w") as f:
        f.write("# Broadcast sweep matrix auto-generated by gen_bcast_sweep.py.\n")
        f.write("# One operation: root=group[0], target=entire group.\n")
        f.write(f"Nodes {nodes}\n")
        f.write("Grp " + " ".join(str(m) for m in group) + "\n")
        f.write("Connections 1\n")
        # src=0 (index into the group -> member[0] is the root).
        # dst=0 (group index, we only declare one group).
        f.write(
            f"0->0 id 1 start_bcast 0 size {payload_bytes}\n"
        )


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--out",
        default="bcast_sweep",
        help="Output directory (relative to cwd)",
    )
    p.add_argument(
        "--nodes",
        type=int,
        nargs="+",
        default=[16, 128],
        help="Node counts to generate matrices for (must be valid "
        "fat-tree sizes: 16, 128, 1024, ...)",
    )
    p.add_argument(
        "--group-sizes",
        type=int,
        nargs="+",
        default=[2, 4, 8, 16, 32, 64, 128],
        help="Group sizes to sweep over (capped to nodes per topology)",
    )
    p.add_argument(
        "--payload-bytes",
        type=int,
        default=4096,
        help="Bytes per broadcast operation (phase-one: single MTU)",
    )
    p.add_argument(
        "--reps",
        type=int,
        default=10,
        help="Independent random-group matrices per (nodes, group_size)",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=0xC0FFEE,
        help="Root RNG seed for group-member selection",
    )
    args = p.parse_args()

    os.makedirs(args.out, exist_ok=True)
    # Derive a distinct sub-RNG per rep so the sweep is reproducible
    # but different reps see different group memberships.
    base_rng = random.Random(args.seed)

    manifest_lines = []
    for nodes in sorted(set(args.nodes)):
        for g in sorted(set(args.group_sizes)):
            if g > nodes or g < 2:
                continue
            for rep in range(args.reps):
                rep_rng = random.Random(base_rng.random())
                group = choose_group(nodes, g, rep_rng)
                filename = f"bcast_n{nodes}_g{g}_r{rep}.cm"
                path = os.path.join(args.out, filename)
                write_cm(path, nodes, group, args.payload_bytes)
                manifest_lines.append(f"{nodes} {g} {rep} {path}")
            print(
                f"n={nodes} g={g}: wrote {args.reps} matrices "
                f"(bcast_n{nodes}_g{g}_r0..{args.reps-1}.cm)"
            )

    manifest_path = os.path.join(args.out, "manifest.txt")
    with open(manifest_path, "w") as f:
        f.write("# nodes group_size rep path\n")
        for line in manifest_lines:
            f.write(line + "\n")
    print(f"\nmanifest: {manifest_path}  ({len(manifest_lines)} matrices)")


if __name__ == "__main__":
    main()
