/* Generated by re2c 4.5.1 on Wed Jun 17 10:13:41 2026 */
#line 1 "LogGOPSim/txt2bin.re"
#include <map>
#include <math.h>
#include <string>
#include <limits>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <inttypes.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <sys/types.h>

#include "Goal.hpp"
#include "cmdline_txt2bin.h"

typedef unsigned int uint;
typedef unsigned char uchar;

#define	BSIZE	10240

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL(n)	{cursor = fill(s, cursor, n);}

#define	RET(i)	{s->cur = cursor; return i;}

gengetopt_args_info args_info;

typedef struct Scanner {
    FILE*		fd;
    uchar		*bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint		line;
	int			rank;
	uint32_t 	curr_rank, num_ranks;
	Goal*		schedule;
	std::map<std::string, goalop_t>* idtbl;
} Scanner;

typedef struct Item {
	char type;
	uint32_t coll_group;     // Phase 4: collective group id
	uint32_t coll_instance;  // Phase 4: shared op id across the group's ranks
	int coll_root;           // Phase 4: root host, -1 = rootless
	char *label1;
	char *label2;
	uint64_t size;
	uint32_t target;
	uint32_t tag;
	uint8_t cpu;
	uint8_t nic;	
} Item;

enum OpTypes {
	Undefined,
	SendOp,
	RecvOp,
	LoclOp,
	StartDependency,
	Dependency,
	BcastOp,
	ReduceOp,
	AllreduceOp,
	ReduceScatterOp,
	AllgatherOp
};

inline uint64_t add_number(unsigned char *s, unsigned char *e) {

	uint64_t num = 0;	
	--s;
	while(++s < e) num = num * 10 + (*s - '0');

	return num;
}

inline void insert_id(Scanner *s, char *id, goalop_t op) {

	s->idtbl->insert(std::make_pair(std::string(id), op));
	free(id);
}

inline goalop_t retrieve_id(Scanner *s, char *id) {

	std::map<std::string, goalop_t>::iterator it;
	it = s->idtbl->find(std::string(id));
	if (it == s->idtbl->end()) {
		fprintf(stderr, "A dependency references label %s, which is undefined!\n", id);
		exit(EXIT_FAILURE);
	}
	free(id);
	return it->second;
} 

void process_item(Scanner *s, Item *item) {

/*
	printf("Parsed Item:\n");
	printf("  Type: ");
	if (item->type == Undefined) printf("Undefined\n");
	if (item->type == SendOp) printf("Send\n");
	if (item->type == RecvOp) printf("Recv\n");
	if (item->type == LoclOp) printf("LoclOp\n");
	if (item->type == StartDependency) printf("IRequires\n");
	if (item->type == Dependency) printf("Requires\n");
	printf("  Label1: %s\n", item->label1);
	printf("  Label2: %s\n", item->label2);
	printf("  Size: %i\n", item->size);
	printf("  Target: %i\n", item->target);
	printf("  Tag: %i\n", item->tag);
	printf("  CPU: %i\n", item->cpu);
	printf("  NIC: %i\n", item->nic);
*/
	
	goalop_t op, op2;

	switch (item->type) {
		case Undefined:
			fprintf(stderr, "Error while parsing, attempt to add a undefined operation\n");
			exit(EXIT_FAILURE);
			break;
		case SendOp:
			op = s->schedule->Send(s->rank, item->target, item->size, item->tag, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		case RecvOp:
			op = s->schedule->Recv(item->target, s->rank, item->size, item->tag, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		case LoclOp:
			op = s->schedule->Calc(s->rank, item->size, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		case StartDependency:
			op = retrieve_id(s, item->label1);
			op2 = retrieve_id(s, item->label2);
			assert(op != NULL);
			assert(op2 != NULL);
			s->schedule->StartDependency(op, op2);
			break;
		case Dependency:
			op = retrieve_id(s, item->label1);
			op2 = retrieve_id(s, item->label2);
			assert(op != NULL);
			assert(op2 != NULL);
			s->schedule->Dependency(op, op2);
			break;
		case BcastOp:
			op = s->schedule->Collective(OPTYPE_BCAST, item->coll_group, item->size, item->coll_instance, item->coll_root, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		case ReduceOp:
			op = s->schedule->Collective(OPTYPE_REDUCE, item->coll_group, item->size, item->coll_instance, item->coll_root, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		case AllreduceOp:
			op = s->schedule->Collective(OPTYPE_ALLREDUCE, item->coll_group, item->size, item->coll_instance, item->coll_root, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		case ReduceScatterOp:
			op = s->schedule->Collective(OPTYPE_REDUCE_SCATTER, item->coll_group, item->size, item->coll_instance, item->coll_root, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		case AllgatherOp:
			op = s->schedule->Collective(OPTYPE_ALLGATHER, item->coll_group, item->size, item->coll_instance, item->coll_root, item->cpu, item->nic);
			if (item->label1 != NULL) insert_id(s, item->label1, op);
			break;
		default:
			break;
	}
}

inline char* add_label(unsigned char *s, unsigned char *e) {
	
	char *buf = NULL;

	buf = (char *) malloc((e-s)+1);
	memcpy((void *) buf, (void *) s, (size_t) (e-s));
	buf[e-s] = '\0';
	
	return buf;

}


uchar *fill(Scanner *s, uchar *cursor, int numtoread) {

	if(!s->eof) {
		uint cnt = s->tok - s->bot;
		if(cnt){
			if ((s->lim - s->tok) < abs(s->bot - s->tok)) memcpy(s->bot, s->tok, s->lim - s->tok);
			else memmove(s->bot, s->tok, s->lim - s->tok);
			s->tok = s->bot;
			s->ptr -= cnt;
			cursor -= cnt;
			s->pos -= cnt;
			s->lim -= cnt;
		}
		if((s->top - s->lim) < BSIZE){
			uchar *buf = (uchar*) malloc(((s->lim - s->bot) + BSIZE)*sizeof(uchar));
			if ((s->lim - s->tok) > abs(s->tok - buf)) memmove(buf, s->tok, s->lim - s->tok);
			else memcpy(buf, s->tok, s->lim - s->tok);
			s->tok = buf;
			s->ptr = &buf[s->ptr - s->bot];
			cursor = &buf[cursor - s->bot];
			s->pos = &buf[s->pos - s->bot];
			s->lim = &buf[s->lim - s->bot];
			s->top = &s->lim[BSIZE];
			free(s->bot);
			s->bot = buf;
		}
		cnt = fread((char*) s->lim, 1, BSIZE, s->fd);
		if(cnt != BSIZE) { 
			s->eof = &s->lim[cnt];
			*(s->eof)++ = '\n';
		}
		s->lim += cnt;
		//assert(cnt >= numtoread);
	}
	return cursor;
}

/*
uchar *fill(Scanner *s, uchar *cursor, int numtoread) {
	
	static bool firstcall = true;

	if (firstcall) {
		
		void *buf;
		struct stat statbuf;
		
		int ret = fstat(fileno(s->fd), &statbuf);
		buf = mmap(NULL, statbuf.st_size, PROT_READ, MAP_PRIVATE, fileno(s->fd), 0);
		assert(buf != NULL);
		s->lim = (uchar*) buf;
		s->lim += statbuf.st_size;
		s->eof = s->lim;
		return (uchar*) buf;	   		
	}
	else {
		assert(0==1);
	}
}
*/

int scan(Scanner *s) {

	//uchar *cursor = s->cur;

	static uchar *cursor = NULL;
	Item item;
	int state;

	for (;;) {

s_0:

	if ((cursor == s->eof) and (cursor != NULL)) {
		fprintf(stderr, "Reached the end of the inputfile - did you forget a closing bracket?\n");
		return s->rank;
	}
	
	s->tok = cursor;
	state = 0;
	
	// printf("Entered s_0\n");
	// if (((s->line % 100) == 0) or (s->line < 100)) printf("Line: %i\n", s->line);

	item.type = Undefined;
	item.label1 = NULL;
	item.label2 = NULL;
	item.cpu = 0;
	item.nic = 0;
	item.tag = 0;
	item.coll_group = 0;
	item.coll_instance = 0;
	item.coll_root = -1;


#line 287 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 10) YYFILL(10);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy3;
				case '\n': goto yy5;
				case '\r': goto yy6;
				case '/': goto yy7;
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'o':
				case 'p':
				case 'q':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				case 'c': goto yy11;
				case 'n': goto yy12;
				case 'r': goto yy13;
				case 's': goto yy14;
				case '}': goto yy15;
				default: goto yy1;
			}
yy1:
			++YYCURSOR;
yy2:
#line 326 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 358 "htsim-backend/sim/lgs/txt2bin.cpp"
yy3:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy3;
				default: goto yy4;
			}
yy4:
#line 313 "LogGOPSim/txt2bin.re"
			{ s->tok = cursor; }
#line 371 "htsim-backend/sim/lgs/txt2bin.cpp"
yy5:
			++YYCURSOR;
#line 324 "LogGOPSim/txt2bin.re"
			{ s->line++; continue; }
#line 376 "htsim-backend/sim/lgs/txt2bin.cpp"
yy6:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy5;
				default: goto yy2;
			}
yy7:
			yych = *++YYCURSOR;
			switch (yych) {
				case '*': goto yy16;
				case '/': goto yy17;
				default: goto yy2;
			}
yy8:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
yy9:
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				default: goto yy10;
			}
yy10:
#line 320 "LogGOPSim/txt2bin.re"
			{ item.label1 = add_label(s->tok, cursor); goto s_1; }
#line 464 "htsim-backend/sim/lgs/txt2bin.cpp"
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'a': goto yy18;
				case 'o': goto yy19;
				default: goto yy9;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy20;
				default: goto yy9;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'a': goto yy21;
				case 'e': goto yy22;
				default: goto yy9;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy23;
				default: goto yy9;
			}
yy15:
			++YYCURSOR;
#line 325 "LogGOPSim/txt2bin.re"
			{ if (s->rank == -1) goto s_err; int oldrank = s->rank; s->rank = -1; return oldrank; }
#line 495 "htsim-backend/sim/lgs/txt2bin.cpp"
yy16:
			++YYCURSOR;
#line 322 "LogGOPSim/txt2bin.re"
			{ goto s_24; }
#line 500 "htsim-backend/sim/lgs/txt2bin.cpp"
yy17:
			++YYCURSOR;
#line 321 "LogGOPSim/txt2bin.re"
			{ goto s_23; }
#line 505 "htsim-backend/sim/lgs/txt2bin.cpp"
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'l': goto yy24;
				default: goto yy9;
			}
yy19:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'l': goto yy25;
				default: goto yy9;
			}
yy20:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'm': goto yy26;
				default: goto yy9;
			}
yy21:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'n': goto yy27;
				default: goto yy9;
			}
yy22:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy28;
				default: goto yy9;
			}
yy23:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'n': goto yy29;
				default: goto yy9;
			}
yy24:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy30;
				default: goto yy9;
			}
yy25:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'l': goto yy32;
				default: goto yy9;
			}
yy26:
			yych = *++YYCURSOR;
			switch (yych) {
				case '_': goto yy34;
				default: goto yy9;
			}
yy27:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'k': goto yy35;
				default: goto yy9;
			}
yy28:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'v': goto yy37;
				default: goto yy9;
			}
yy29:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'd': goto yy39;
				default: goto yy9;
			}
yy30:
			yych = *++YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				default: goto yy31;
			}
yy31:
#line 316 "LogGOPSim/txt2bin.re"
			{ item.type = LoclOp;  goto s_3; }
#line 649 "htsim-backend/sim/lgs/txt2bin.cpp"
yy32:
			yych = *++YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				default: goto yy33;
			}
yy33:
#line 317 "LogGOPSim/txt2bin.re"
			{ goto s_30; }
#line 721 "htsim-backend/sim/lgs/txt2bin.cpp"
yy34:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'r': goto yy41;
				default: goto yy9;
			}
yy35:
			yych = *++YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				default: goto yy36;
			}
yy36:
#line 318 "LogGOPSim/txt2bin.re"
			{ goto s_20; }
#line 799 "htsim-backend/sim/lgs/txt2bin.cpp"
yy37:
			yych = *++YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				default: goto yy38;
			}
yy38:
#line 315 "LogGOPSim/txt2bin.re"
			{ item.type = RecvOp;  goto s_2; }
#line 871 "htsim-backend/sim/lgs/txt2bin.cpp"
yy39:
			yych = *++YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				default: goto yy40;
			}
yy40:
#line 314 "LogGOPSim/txt2bin.re"
			{ item.type = SendOp;  goto s_2; }
#line 943 "htsim-backend/sim/lgs/txt2bin.cpp"
yy41:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'a': goto yy42;
				default: goto yy9;
			}
yy42:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'n': goto yy43;
				default: goto yy9;
			}
yy43:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'k': goto yy44;
				default: goto yy9;
			}
yy44:
			yych = *++YYCURSOR;
			switch (yych) {
				case 's': goto yy45;
				default: goto yy9;
			}
yy45:
			yych = *++YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy8;
				default: goto yy46;
			}
yy46:
#line 319 "LogGOPSim/txt2bin.re"
			{ goto s_22; }
#line 1039 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 327 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_1:
	state =1;

	// printf("Entered s_1\n");


#line 1052 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy50;
				case ':': goto yy52;
				case 'i': goto yy53;
				case 'r': goto yy54;
				default: goto yy48;
			}
yy48:
			++YYCURSOR;
yy49:
#line 341 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1070 "htsim-backend/sim/lgs/txt2bin.cpp"
yy50:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy50;
				default: goto yy51;
			}
yy51:
#line 337 "LogGOPSim/txt2bin.re"
			{ goto s_1; }
#line 1083 "htsim-backend/sim/lgs/txt2bin.cpp"
yy52:
			++YYCURSOR;
#line 338 "LogGOPSim/txt2bin.re"
			{ goto s_4; }
#line 1088 "htsim-backend/sim/lgs/txt2bin.cpp"
yy53:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'r': goto yy55;
				default: goto yy49;
			}
yy54:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'e': goto yy57;
				default: goto yy49;
			}
yy55:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy58;
				default: goto yy56;
			}
yy56:
			YYCURSOR = YYMARKER;
			goto yy49;
yy57:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'q': goto yy59;
				default: goto yy56;
			}
yy58:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'q': goto yy60;
				default: goto yy56;
			}
yy59:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy61;
				default: goto yy56;
			}
yy60:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy62;
				default: goto yy56;
			}
yy61:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'i': goto yy63;
				default: goto yy56;
			}
yy62:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'i': goto yy64;
				default: goto yy56;
			}
yy63:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'r': goto yy65;
				default: goto yy56;
			}
yy64:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'r': goto yy66;
				default: goto yy56;
			}
yy65:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy67;
				default: goto yy56;
			}
yy66:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy68;
				default: goto yy56;
			}
yy67:
			yych = *++YYCURSOR;
			switch (yych) {
				case 's': goto yy69;
				default: goto yy56;
			}
yy68:
			yych = *++YYCURSOR;
			switch (yych) {
				case 's': goto yy70;
				default: goto yy56;
			}
yy69:
			++YYCURSOR;
#line 339 "LogGOPSim/txt2bin.re"
			{ item.type = Dependency;       goto s_5; }
#line 1186 "htsim-backend/sim/lgs/txt2bin.cpp"
yy70:
			++YYCURSOR;
#line 340 "LogGOPSim/txt2bin.re"
			{ item.type = StartDependency;  goto s_5; }
#line 1191 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 342 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_2:
	state=2;

	// printf("Entered s_2\n");

		s->tok = cursor;

#line 1204 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy73;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy75;
				default: goto yy72;
			}
yy72:
			++YYCURSOR;
#line 354 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1228 "htsim-backend/sim/lgs/txt2bin.cpp"
yy73:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy73;
				default: goto yy74;
			}
yy74:
#line 352 "LogGOPSim/txt2bin.re"
			{ goto s_2; }
#line 1241 "htsim-backend/sim/lgs/txt2bin.cpp"
yy75:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy75;
				default: goto yy76;
			}
yy76:
#line 353 "LogGOPSim/txt2bin.re"
			{ item.size = add_number(s->tok, cursor); goto s_10; }
#line 1262 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 355 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_3:
	state = 3;
	// printf("Entered s_3\n");

		s->tok = cursor;

#line 1275 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy79;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy81;
				default: goto yy78;
			}
yy78:
			++YYCURSOR;
#line 367 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1299 "htsim-backend/sim/lgs/txt2bin.cpp"
yy79:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy79;
				default: goto yy80;
			}
yy80:
#line 365 "LogGOPSim/txt2bin.re"
			{ goto s_3; }
#line 1312 "htsim-backend/sim/lgs/txt2bin.cpp"
yy81:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy81;
				default: goto yy82;
			}
yy82:
#line 366 "LogGOPSim/txt2bin.re"
			{ item.size = add_number(s->tok, cursor); goto s_7; }
#line 1333 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 368 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_4:
	state = 4;
	// printf("Entered s_4\n");


#line 1345 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy86;
				case 'c': goto yy88;
				case 'r': goto yy89;
				case 's': goto yy90;
				default: goto yy84;
			}
yy84:
			++YYCURSOR;
yy85:
#line 382 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1363 "htsim-backend/sim/lgs/txt2bin.cpp"
yy86:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy86;
				default: goto yy87;
			}
yy87:
#line 377 "LogGOPSim/txt2bin.re"
			{ goto s_4; }
#line 1376 "htsim-backend/sim/lgs/txt2bin.cpp"
yy88:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'a': goto yy91;
				case 'o': goto yy93;
				default: goto yy85;
			}
yy89:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'e': goto yy94;
				default: goto yy85;
			}
yy90:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'e': goto yy95;
				default: goto yy85;
			}
yy91:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'l': goto yy96;
				default: goto yy92;
			}
yy92:
			YYCURSOR = YYMARKER;
			goto yy85;
yy93:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'l': goto yy97;
				default: goto yy92;
			}
yy94:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy98;
				default: goto yy92;
			}
yy95:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'n': goto yy99;
				default: goto yy92;
			}
yy96:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy100;
				default: goto yy92;
			}
yy97:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'l': goto yy101;
				default: goto yy92;
			}
yy98:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'v': goto yy102;
				default: goto yy92;
			}
yy99:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'd': goto yy103;
				default: goto yy92;
			}
yy100:
			++YYCURSOR;
#line 378 "LogGOPSim/txt2bin.re"
			{ item.type = LoclOp; goto s_3; }
#line 1451 "htsim-backend/sim/lgs/txt2bin.cpp"
yy101:
			++YYCURSOR;
#line 379 "LogGOPSim/txt2bin.re"
			{ goto s_30; }
#line 1456 "htsim-backend/sim/lgs/txt2bin.cpp"
yy102:
			++YYCURSOR;
#line 381 "LogGOPSim/txt2bin.re"
			{ item.type = RecvOp; goto s_2; }
#line 1461 "htsim-backend/sim/lgs/txt2bin.cpp"
yy103:
			++YYCURSOR;
#line 380 "LogGOPSim/txt2bin.re"
			{ item.type = SendOp; goto s_2; }
#line 1466 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 383 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_5:
	state =5;
	// printf("Entered s_5\n");

		s->tok = cursor;

#line 1478 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy106;
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy108;
				default: goto yy105;
			}
yy105:
			++YYCURSOR;
#line 394 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1544 "htsim-backend/sim/lgs/txt2bin.cpp"
yy106:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy106;
				default: goto yy107;
			}
yy107:
#line 392 "LogGOPSim/txt2bin.re"
			{ goto s_5; }
#line 1557 "htsim-backend/sim/lgs/txt2bin.cpp"
yy108:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto yy108;
				default: goto yy109;
			}
yy109:
#line 393 "LogGOPSim/txt2bin.re"
			{ item.label2 = add_label(s->tok, cursor); goto s_6; }
#line 1631 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 395 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_6:
	state = 6;
	// printf("Entered s_6\n");


#line 1643 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy113;
				case '\n': goto yy115;
				case '\r': goto yy116;
				default: goto yy111;
			}
yy111:
			++YYCURSOR;
yy112:
#line 406 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1660 "htsim-backend/sim/lgs/txt2bin.cpp"
yy113:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy113;
				default: goto yy114;
			}
yy114:
#line 404 "LogGOPSim/txt2bin.re"
			{ goto s_6; }
#line 1673 "htsim-backend/sim/lgs/txt2bin.cpp"
yy115:
			++YYCURSOR;
#line 405 "LogGOPSim/txt2bin.re"
			{ s->line++; process_item(s, &item); continue; }
#line 1678 "htsim-backend/sim/lgs/txt2bin.cpp"
yy116:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy115;
				default: goto yy112;
			}
		}
#line 407 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_7:
	state = 7;
	// printf("Entered s_7\n");


#line 1696 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy120;
				case '\n': goto yy122;
				case '\r': goto yy123;
				case 'c': goto yy124;
				default: goto yy118;
			}
yy118:
			++YYCURSOR;
yy119:
#line 419 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1714 "htsim-backend/sim/lgs/txt2bin.cpp"
yy120:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy120;
				default: goto yy121;
			}
yy121:
#line 416 "LogGOPSim/txt2bin.re"
			{ goto s_7; }
#line 1727 "htsim-backend/sim/lgs/txt2bin.cpp"
yy122:
			++YYCURSOR;
#line 418 "LogGOPSim/txt2bin.re"
			{ s->line++; process_item(s, &item); continue; }
#line 1732 "htsim-backend/sim/lgs/txt2bin.cpp"
yy123:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy122;
				default: goto yy119;
			}
yy124:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'p': goto yy125;
				default: goto yy119;
			}
yy125:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy127;
				default: goto yy126;
			}
yy126:
			YYCURSOR = YYMARKER;
			goto yy119;
yy127:
			++YYCURSOR;
#line 417 "LogGOPSim/txt2bin.re"
			{ goto s_8; }
#line 1758 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 420 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_8:
	state =8;
	// printf("Entered s_8\n");
	
	s->tok = cursor;


#line 1772 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy130;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy132;
				default: goto yy129;
			}
yy129:
			++YYCURSOR;
#line 433 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1796 "htsim-backend/sim/lgs/txt2bin.cpp"
yy130:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy130;
				default: goto yy131;
			}
yy131:
#line 431 "LogGOPSim/txt2bin.re"
			{ goto s_8; }
#line 1809 "htsim-backend/sim/lgs/txt2bin.cpp"
yy132:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy132;
				default: goto yy133;
			}
yy133:
#line 432 "LogGOPSim/txt2bin.re"
			{ item.cpu = add_number(s->tok, cursor); goto s_9; }
#line 1830 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 434 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_9:
	state=9;
	// printf("Entered s_9\n");


#line 1842 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy137;
				case '\n': goto yy139;
				case '\r': goto yy140;
				default: goto yy135;
			}
yy135:
			++YYCURSOR;
yy136:
#line 445 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1859 "htsim-backend/sim/lgs/txt2bin.cpp"
yy137:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy137;
				default: goto yy138;
			}
yy138:
#line 443 "LogGOPSim/txt2bin.re"
			{ goto s_9; }
#line 1872 "htsim-backend/sim/lgs/txt2bin.cpp"
yy139:
			++YYCURSOR;
#line 444 "LogGOPSim/txt2bin.re"
			{ s->line++; process_item(s, &item); continue; }
#line 1877 "htsim-backend/sim/lgs/txt2bin.cpp"
yy140:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy139;
				default: goto yy136;
			}
		}
#line 446 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_10:
	state=10;
	// printf("Entered s_10\n");


#line 1895 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy143;
				case 'b': goto yy145;
				default: goto yy142;
			}
yy142:
			++YYCURSOR;
#line 457 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1910 "htsim-backend/sim/lgs/txt2bin.cpp"
yy143:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy143;
				default: goto yy144;
			}
yy144:
#line 455 "LogGOPSim/txt2bin.re"
			{ goto s_10; }
#line 1923 "htsim-backend/sim/lgs/txt2bin.cpp"
yy145:
			++YYCURSOR;
#line 456 "LogGOPSim/txt2bin.re"
			{ goto s_11; }
#line 1928 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 458 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_11:
	state = 11;
	// printf("Entered s_11\n");


#line 1940 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy149;
				case 'f': goto yy151;
				case 't': goto yy152;
				default: goto yy147;
			}
yy147:
			++YYCURSOR;
yy148:
#line 470 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 1957 "htsim-backend/sim/lgs/txt2bin.cpp"
yy149:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy149;
				default: goto yy150;
			}
yy150:
#line 467 "LogGOPSim/txt2bin.re"
			{ goto s_11; }
#line 1970 "htsim-backend/sim/lgs/txt2bin.cpp"
yy151:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'r': goto yy153;
				default: goto yy148;
			}
yy152:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'o': goto yy155;
				default: goto yy148;
			}
yy153:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'o': goto yy156;
				default: goto yy154;
			}
yy154:
			YYCURSOR = YYMARKER;
			goto yy148;
yy155:
			++YYCURSOR;
#line 468 "LogGOPSim/txt2bin.re"
			{ if (item.type == SendOp) {goto s_12;} else {goto s_err;}; }
#line 1996 "htsim-backend/sim/lgs/txt2bin.cpp"
yy156:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'm': goto yy157;
				default: goto yy154;
			}
yy157:
			++YYCURSOR;
#line 469 "LogGOPSim/txt2bin.re"
			{ if (item.type == RecvOp) {goto s_12;} else {goto s_err;}; }
#line 2007 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 471 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_12:
	state = 12;	
	// printf("Entered s_12\n");
	
	s->tok = cursor;


#line 2021 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy161;
				case '-': goto yy163;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy164;
				default: goto yy159;
			}
yy159:
			++YYCURSOR;
yy160:
#line 485 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2047 "htsim-backend/sim/lgs/txt2bin.cpp"
yy161:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy161;
				default: goto yy162;
			}
yy162:
#line 482 "LogGOPSim/txt2bin.re"
			{ goto s_12; }
#line 2060 "htsim-backend/sim/lgs/txt2bin.cpp"
yy163:
			yych = *++YYCURSOR;
			switch (yych) {
				case '1': goto yy166;
				default: goto yy160;
			}
yy164:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy164;
				default: goto yy165;
			}
yy165:
#line 484 "LogGOPSim/txt2bin.re"
			{ item.target = add_number(s->tok, cursor); goto s_13; }
#line 2087 "htsim-backend/sim/lgs/txt2bin.cpp"
yy166:
			++YYCURSOR;
#line 483 "LogGOPSim/txt2bin.re"
			{if (item.type == RecvOp) {item.target = std::numeric_limits<uint32_t>::max(); goto s_13;} else {goto s_err;}; }
#line 2092 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 486 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_13:
	state = 13;
	// printf("Entered s_13\n");


#line 2104 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy170;
				case '\n': goto yy172;
				case '\r': goto yy173;
				case 'c': goto yy174;
				case 'n': goto yy175;
				case 't': goto yy176;
				default: goto yy168;
			}
yy168:
			++YYCURSOR;
yy169:
#line 500 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2124 "htsim-backend/sim/lgs/txt2bin.cpp"
yy170:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy170;
				default: goto yy171;
			}
yy171:
#line 495 "LogGOPSim/txt2bin.re"
			{ goto s_13; }
#line 2137 "htsim-backend/sim/lgs/txt2bin.cpp"
yy172:
			++YYCURSOR;
#line 499 "LogGOPSim/txt2bin.re"
			{ s->line++; process_item(s, &item); continue; }
#line 2142 "htsim-backend/sim/lgs/txt2bin.cpp"
yy173:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy172;
				default: goto yy169;
			}
yy174:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'p': goto yy177;
				default: goto yy169;
			}
yy175:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'i': goto yy179;
				default: goto yy169;
			}
yy176:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'a': goto yy180;
				default: goto yy169;
			}
yy177:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy181;
				default: goto yy178;
			}
yy178:
			YYCURSOR = YYMARKER;
			goto yy169;
yy179:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy182;
				default: goto yy178;
			}
yy180:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'g': goto yy183;
				default: goto yy178;
			}
yy181:
			++YYCURSOR;
#line 497 "LogGOPSim/txt2bin.re"
			{ goto s_16; }
#line 2192 "htsim-backend/sim/lgs/txt2bin.cpp"
yy182:
			++YYCURSOR;
#line 498 "LogGOPSim/txt2bin.re"
			{ goto s_18; }
#line 2197 "htsim-backend/sim/lgs/txt2bin.cpp"
yy183:
			++YYCURSOR;
#line 496 "LogGOPSim/txt2bin.re"
			{ goto s_14; }
#line 2202 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 501 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_30:
	state = 30;
	// coll: collective kind keyword

#line 2213 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			if ((YYLIMIT - YYCURSOR) < 14) YYFILL(14);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy187;
				case 'a': goto yy189;
				case 'b': goto yy190;
				case 'r': goto yy191;
				default: goto yy185;
			}
yy185:
			++YYCURSOR;
yy186:
#line 515 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2232 "htsim-backend/sim/lgs/txt2bin.cpp"
yy187:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy187;
				default: goto yy188;
			}
yy188:
#line 509 "LogGOPSim/txt2bin.re"
			{ goto s_30; }
#line 2245 "htsim-backend/sim/lgs/txt2bin.cpp"
yy189:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'l': goto yy192;
				default: goto yy186;
			}
yy190:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'c': goto yy194;
				default: goto yy186;
			}
yy191:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'e': goto yy195;
				default: goto yy186;
			}
yy192:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'l': goto yy196;
				default: goto yy193;
			}
yy193:
			YYCURSOR = YYMARKER;
			if (yyaccept == 0) goto yy186;
			else goto yy210;
yy194:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'a': goto yy197;
				default: goto yy193;
			}
yy195:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'd': goto yy198;
				default: goto yy193;
			}
yy196:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'g': goto yy199;
				case 'r': goto yy200;
				default: goto yy193;
			}
yy197:
			yych = *++YYCURSOR;
			switch (yych) {
				case 's': goto yy201;
				default: goto yy193;
			}
yy198:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy202;
				default: goto yy193;
			}
yy199:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'a': goto yy203;
				default: goto yy193;
			}
yy200:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy204;
				default: goto yy193;
			}
yy201:
			yych = *++YYCURSOR;
			switch (yych) {
				case 't': goto yy205;
				default: goto yy193;
			}
yy202:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy206;
				default: goto yy193;
			}
yy203:
			yych = *++YYCURSOR;
			switch (yych) {
				case 't': goto yy207;
				default: goto yy193;
			}
yy204:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'd': goto yy208;
				default: goto yy193;
			}
yy205:
			++YYCURSOR;
#line 512 "LogGOPSim/txt2bin.re"
			{ item.type = BcastOp;         goto s_31; }
#line 2348 "htsim-backend/sim/lgs/txt2bin.cpp"
yy206:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy209;
				default: goto yy193;
			}
yy207:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'h': goto yy211;
				default: goto yy193;
			}
yy208:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy212;
				default: goto yy193;
			}
yy209:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case '_': goto yy213;
				default: goto yy210;
			}
yy210:
#line 514 "LogGOPSim/txt2bin.re"
			{ item.type = ReduceOp;        goto s_31; }
#line 2377 "htsim-backend/sim/lgs/txt2bin.cpp"
yy211:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy214;
				default: goto yy193;
			}
yy212:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy215;
				default: goto yy193;
			}
yy213:
			yych = *++YYCURSOR;
			switch (yych) {
				case 's': goto yy216;
				default: goto yy193;
			}
yy214:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'r': goto yy217;
				default: goto yy193;
			}
yy215:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy218;
				default: goto yy193;
			}
yy216:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy219;
				default: goto yy193;
			}
yy217:
			++YYCURSOR;
#line 511 "LogGOPSim/txt2bin.re"
			{ item.type = AllgatherOp;     goto s_31; }
#line 2418 "htsim-backend/sim/lgs/txt2bin.cpp"
yy218:
			++YYCURSOR;
#line 510 "LogGOPSim/txt2bin.re"
			{ item.type = AllreduceOp;     goto s_31; }
#line 2423 "htsim-backend/sim/lgs/txt2bin.cpp"
yy219:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'a': goto yy220;
				default: goto yy193;
			}
yy220:
			yych = *++YYCURSOR;
			switch (yych) {
				case 't': goto yy221;
				default: goto yy193;
			}
yy221:
			yych = *++YYCURSOR;
			switch (yych) {
				case 't': goto yy222;
				default: goto yy193;
			}
yy222:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'e': goto yy223;
				default: goto yy193;
			}
yy223:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'r': goto yy224;
				default: goto yy193;
			}
yy224:
			++YYCURSOR;
#line 513 "LogGOPSim/txt2bin.re"
			{ item.type = ReduceScatterOp; goto s_31; }
#line 2458 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 516 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_31:
	state = 31;
	s->tok = cursor;

#line 2468 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy227;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy229;
				default: goto yy226;
			}
yy226:
			++YYCURSOR;
#line 525 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2492 "htsim-backend/sim/lgs/txt2bin.cpp"
yy227:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy227;
				default: goto yy228;
			}
yy228:
#line 523 "LogGOPSim/txt2bin.re"
			{ goto s_31; }
#line 2505 "htsim-backend/sim/lgs/txt2bin.cpp"
yy229:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy229;
				default: goto yy230;
			}
yy230:
#line 524 "LogGOPSim/txt2bin.re"
			{ item.size = add_number(s->tok, cursor); goto s_32; }
#line 2526 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 526 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_32:
	state = 32;

#line 2535 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy233;
				case 'b': goto yy235;
				default: goto yy232;
			}
yy232:
			++YYCURSOR;
#line 534 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2550 "htsim-backend/sim/lgs/txt2bin.cpp"
yy233:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy233;
				default: goto yy234;
			}
yy234:
#line 532 "LogGOPSim/txt2bin.re"
			{ goto s_32; }
#line 2563 "htsim-backend/sim/lgs/txt2bin.cpp"
yy235:
			++YYCURSOR;
#line 533 "LogGOPSim/txt2bin.re"
			{ goto s_33; }
#line 2568 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 535 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_33:
	state = 33;
	s->tok = cursor;

#line 2578 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy238;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy240;
				default: goto yy237;
			}
yy237:
			++YYCURSOR;
#line 544 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2602 "htsim-backend/sim/lgs/txt2bin.cpp"
yy238:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy238;
				default: goto yy239;
			}
yy239:
#line 542 "LogGOPSim/txt2bin.re"
			{ goto s_33; }
#line 2615 "htsim-backend/sim/lgs/txt2bin.cpp"
yy240:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy240;
				default: goto yy241;
			}
yy241:
#line 543 "LogGOPSim/txt2bin.re"
			{ item.coll_group = add_number(s->tok, cursor); goto s_34; }
#line 2636 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 545 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_34:
	state = 34;
	s->tok = cursor;

#line 2646 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy244;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy246;
				default: goto yy243;
			}
yy243:
			++YYCURSOR;
#line 554 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2670 "htsim-backend/sim/lgs/txt2bin.cpp"
yy244:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy244;
				default: goto yy245;
			}
yy245:
#line 552 "LogGOPSim/txt2bin.re"
			{ goto s_34; }
#line 2683 "htsim-backend/sim/lgs/txt2bin.cpp"
yy246:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy246;
				default: goto yy247;
			}
yy247:
#line 553 "LogGOPSim/txt2bin.re"
			{ item.coll_instance = add_number(s->tok, cursor); goto s_35; }
#line 2704 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 555 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_35:
	state = 35;
	s->tok = cursor;

#line 2714 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy251;
				case '-': goto yy253;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy254;
				default: goto yy249;
			}
yy249:
			++YYCURSOR;
yy250:
#line 565 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2740 "htsim-backend/sim/lgs/txt2bin.cpp"
yy251:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy251;
				default: goto yy252;
			}
yy252:
#line 562 "LogGOPSim/txt2bin.re"
			{ goto s_35; }
#line 2753 "htsim-backend/sim/lgs/txt2bin.cpp"
yy253:
			yych = *++YYCURSOR;
			switch (yych) {
				case '1': goto yy256;
				default: goto yy250;
			}
yy254:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy254;
				default: goto yy255;
			}
yy255:
#line 564 "LogGOPSim/txt2bin.re"
			{ item.coll_root = (int) add_number(s->tok, cursor); goto s_13; }
#line 2780 "htsim-backend/sim/lgs/txt2bin.cpp"
yy256:
			++YYCURSOR;
#line 563 "LogGOPSim/txt2bin.re"
			{ item.coll_root = -1; goto s_13; }
#line 2785 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 566 "LogGOPSim/txt2bin.re"

	assert(0==1); //We should never reach this line

s_14:
	state = 14;
	// printf("Entered s_14\n");

	s->tok = cursor;


#line 2798 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy260;
				case '-': goto yy262;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy263;
				default: goto yy258;
			}
yy258:
			++YYCURSOR;
yy259:
#line 579 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2824 "htsim-backend/sim/lgs/txt2bin.cpp"
yy260:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy260;
				default: goto yy261;
			}
yy261:
#line 576 "LogGOPSim/txt2bin.re"
			{ goto s_14; }
#line 2837 "htsim-backend/sim/lgs/txt2bin.cpp"
yy262:
			yych = *++YYCURSOR;
			switch (yych) {
				case '1': goto yy265;
				default: goto yy259;
			}
yy263:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy263;
				default: goto yy264;
			}
yy264:
#line 578 "LogGOPSim/txt2bin.re"
			{ item.tag = add_number(s->tok, cursor); goto s_15; }
#line 2864 "htsim-backend/sim/lgs/txt2bin.cpp"
yy265:
			++YYCURSOR;
#line 577 "LogGOPSim/txt2bin.re"
			{ item.tag = std::numeric_limits<uint32_t>::max(); goto s_15; }
#line 2869 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 580 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_15:
	state =15;
	// printf("Entered s_15\n");


#line 2881 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy269;
				case '\n': goto yy271;
				case '\r': goto yy272;
				case 'c': goto yy273;
				case 'n': goto yy274;
				default: goto yy267;
			}
yy267:
			++YYCURSOR;
yy268:
#line 593 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2900 "htsim-backend/sim/lgs/txt2bin.cpp"
yy269:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy269;
				default: goto yy270;
			}
yy270:
#line 589 "LogGOPSim/txt2bin.re"
			{ goto s_15; }
#line 2913 "htsim-backend/sim/lgs/txt2bin.cpp"
yy271:
			++YYCURSOR;
#line 592 "LogGOPSim/txt2bin.re"
			{ s->line++; process_item(s, &item); continue; }
#line 2918 "htsim-backend/sim/lgs/txt2bin.cpp"
yy272:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy271;
				default: goto yy268;
			}
yy273:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'p': goto yy275;
				default: goto yy268;
			}
yy274:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'i': goto yy277;
				default: goto yy268;
			}
yy275:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'u': goto yy278;
				default: goto yy276;
			}
yy276:
			YYCURSOR = YYMARKER;
			goto yy268;
yy277:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy279;
				default: goto yy276;
			}
yy278:
			++YYCURSOR;
#line 590 "LogGOPSim/txt2bin.re"
			{ goto s_16; }
#line 2956 "htsim-backend/sim/lgs/txt2bin.cpp"
yy279:
			++YYCURSOR;
#line 591 "LogGOPSim/txt2bin.re"
			{ goto s_18; }
#line 2961 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 594 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_16:
	state = 16;
	// printf("Entered s_16\n");
	
	s->tok = cursor;


#line 2975 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy282;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy284;
				default: goto yy281;
			}
yy281:
			++YYCURSOR;
#line 607 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 2999 "htsim-backend/sim/lgs/txt2bin.cpp"
yy282:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy282;
				default: goto yy283;
			}
yy283:
#line 605 "LogGOPSim/txt2bin.re"
			{ goto s_16; }
#line 3012 "htsim-backend/sim/lgs/txt2bin.cpp"
yy284:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy284;
				default: goto yy285;
			}
yy285:
#line 606 "LogGOPSim/txt2bin.re"
			{ item.cpu = add_number(s->tok, cursor); goto s_17; }
#line 3033 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 608 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_17:
	state = 17;
	// printf("Entered s_17\n");
	

#line 3045 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy289;
				case '\n': goto yy291;
				case '\r': goto yy292;
				case 'n': goto yy293;
				default: goto yy287;
			}
yy287:
			++YYCURSOR;
yy288:
#line 620 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 3063 "htsim-backend/sim/lgs/txt2bin.cpp"
yy289:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy289;
				default: goto yy290;
			}
yy290:
#line 617 "LogGOPSim/txt2bin.re"
			{ goto s_17; }
#line 3076 "htsim-backend/sim/lgs/txt2bin.cpp"
yy291:
			++YYCURSOR;
#line 619 "LogGOPSim/txt2bin.re"
			{ s->line++; process_item(s, &item); continue; }
#line 3081 "htsim-backend/sim/lgs/txt2bin.cpp"
yy292:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy291;
				default: goto yy288;
			}
yy293:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
				case 'i': goto yy294;
				default: goto yy288;
			}
yy294:
			yych = *++YYCURSOR;
			switch (yych) {
				case 'c': goto yy296;
				default: goto yy295;
			}
yy295:
			YYCURSOR = YYMARKER;
			goto yy288;
yy296:
			++YYCURSOR;
#line 618 "LogGOPSim/txt2bin.re"
			{ goto s_18; }
#line 3107 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 621 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_18:
	state = 18;
	// printf("Entered s_18\n");
	
	s->tok = cursor;


#line 3121 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy299;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy301;
				default: goto yy298;
			}
yy298:
			++YYCURSOR;
#line 634 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 3145 "htsim-backend/sim/lgs/txt2bin.cpp"
yy299:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy299;
				default: goto yy300;
			}
yy300:
#line 632 "LogGOPSim/txt2bin.re"
			{ goto s_18; }
#line 3158 "htsim-backend/sim/lgs/txt2bin.cpp"
yy301:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy301;
				default: goto yy302;
			}
yy302:
#line 633 "LogGOPSim/txt2bin.re"
			{ item.nic = add_number(s->tok, cursor); goto s_19; }
#line 3179 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 635 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_19:
	state = 19;
	// printf("Entered s_19\n");


#line 3191 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy306;
				case '\n': goto yy308;
				case '\r': goto yy309;
				default: goto yy304;
			}
yy304:
			++YYCURSOR;
yy305:
#line 646 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 3208 "htsim-backend/sim/lgs/txt2bin.cpp"
yy306:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy306;
				default: goto yy307;
			}
yy307:
#line 644 "LogGOPSim/txt2bin.re"
			{ goto s_19; }
#line 3221 "htsim-backend/sim/lgs/txt2bin.cpp"
yy308:
			++YYCURSOR;
#line 645 "LogGOPSim/txt2bin.re"
			{ s->line++; process_item(s, &item); continue; }
#line 3226 "htsim-backend/sim/lgs/txt2bin.cpp"
yy309:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy308;
				default: goto yy305;
			}
		}
#line 647 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_20:
	state = 20;
	// printf("Entered s_20\n");

	s->tok = cursor;


#line 3246 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy312;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy314;
				default: goto yy311;
			}
yy311:
			++YYCURSOR;
#line 660 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 3270 "htsim-backend/sim/lgs/txt2bin.cpp"
yy312:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy312;
				default: goto yy313;
			}
yy313:
#line 658 "LogGOPSim/txt2bin.re"
			{ goto s_20; }
#line 3283 "htsim-backend/sim/lgs/txt2bin.cpp"
yy314:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy314;
				default: goto yy315;
			}
yy315:
#line 659 "LogGOPSim/txt2bin.re"
			{ s->rank = add_number(s->tok, cursor); s->curr_rank = s->rank; goto s_21; }
#line 3304 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 661 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_21:
	state = 21;
	// printf("Entered s_21\n");


#line 3316 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy318;
				case '{': goto yy320;
				default: goto yy317;
			}
yy317:
			++YYCURSOR;
#line 672 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 3331 "htsim-backend/sim/lgs/txt2bin.cpp"
yy318:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy318;
				default: goto yy319;
			}
yy319:
#line 670 "LogGOPSim/txt2bin.re"
			{ goto s_21; }
#line 3344 "htsim-backend/sim/lgs/txt2bin.cpp"
yy320:
			++YYCURSOR;
#line 671 "LogGOPSim/txt2bin.re"
			{ goto s_0; }
#line 3349 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 673 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_22:
	state = 22;
	// printf("Entered s_22\n");

	s->tok = cursor;


#line 3363 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy323;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy325;
				default: goto yy322;
			}
yy322:
			++YYCURSOR;
#line 686 "LogGOPSim/txt2bin.re"
			{ goto s_err; }
#line 3387 "htsim-backend/sim/lgs/txt2bin.cpp"
yy323:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '\t':
				case ' ': goto yy323;
				default: goto yy324;
			}
yy324:
#line 684 "LogGOPSim/txt2bin.re"
			{ goto s_22; }
#line 3400 "htsim-backend/sim/lgs/txt2bin.cpp"
yy325:
			++YYCURSOR;
			if (YYLIMIT <= YYCURSOR) YYFILL(1);
			yych = *YYCURSOR;
			switch (yych) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto yy325;
				default: goto yy326;
			}
yy326:
#line 685 "LogGOPSim/txt2bin.re"
			{ s->num_ranks = add_number(s->tok, cursor); goto s_0; }
#line 3421 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 687 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_23:
	state = 23;
	// printf("Entered s_23\n");


#line 3433 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\n': goto yy330;
				case '\r': goto yy331;
				default: goto yy328;
			}
yy328:
			++YYCURSOR;
yy329:
#line 697 "LogGOPSim/txt2bin.re"
			{ goto s_23; }
#line 3448 "htsim-backend/sim/lgs/txt2bin.cpp"
yy330:
			++YYCURSOR;
#line 696 "LogGOPSim/txt2bin.re"
			{ s->line++; continue;  }
#line 3453 "htsim-backend/sim/lgs/txt2bin.cpp"
yy331:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy330;
				default: goto yy329;
			}
		}
#line 698 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line

s_24:
	state = 24;
	// printf("Entered s_24\n");


#line 3471 "htsim-backend/sim/lgs/txt2bin.cpp"
		{
			YYCTYPE yych;
			if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
			yych = *YYCURSOR;
			switch (yych) {
				case '\n': goto yy335;
				case '\r': goto yy336;
				case '*': goto yy337;
				default: goto yy333;
			}
yy333:
			++YYCURSOR;
yy334:
#line 709 "LogGOPSim/txt2bin.re"
			{ goto s_24; }
#line 3487 "htsim-backend/sim/lgs/txt2bin.cpp"
yy335:
			++YYCURSOR;
#line 708 "LogGOPSim/txt2bin.re"
			{ s->line++; goto s_24;  }
#line 3492 "htsim-backend/sim/lgs/txt2bin.cpp"
yy336:
			yych = *++YYCURSOR;
			switch (yych) {
				case '\n': goto yy335;
				default: goto yy334;
			}
yy337:
			yych = *++YYCURSOR;
			switch (yych) {
				case '/': goto yy338;
				default: goto yy334;
			}
yy338:
			++YYCURSOR;
#line 707 "LogGOPSim/txt2bin.re"
			{ continue; }
#line 3509 "htsim-backend/sim/lgs/txt2bin.cpp"
		}
#line 710 "LogGOPSim/txt2bin.re"


	assert(0==1); //We should never reach this line
	
s_err:

	fprintf(stderr, "Error in line %i:\n", s->line);
	
	uchar* nlbef = s->bot;
	uchar* nlaft = s->lim;
	// find the last newline before the error
	uchar* c = cursor-2;
	while (c>s->bot) {
		c--;
		if (*c == '\n') {
			nlbef = c;
			break;
		}
	}
	// find the next newline after the error
	c = cursor-2;
	while (c<s->lim) {
		c++;
		if (*c == '\n') {
			nlaft = c;
			break;
		}
	}

	for (uchar* c = nlbef+1; c<nlaft; c++) {
		fprintf(stderr, "%c", *c);
	}
	fprintf(stderr, "\n");

	for (int cnt=0; cnt<(cursor-2)-nlbef; cnt++) {
		fprintf(stderr, " ");
	}
	fprintf(stderr, "^\n");


	switch(state) {
		case 0:
			fprintf(stderr,"Expected: \"rank\", \"num_ranks\", \"calc\", \"send\", \"recv\", an identifier, \"}\" or \"\\n\"\n");
			break;
		case 1:
			fprintf(stderr,"Expected: \":\", \"requires\" or \"irequires\"\n");
			break;
		case 2:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 3:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 4:
			fprintf(stderr,"Expected: \"calc\", \"send\" or \"recv\"\n");
			break;
		case 5:
			fprintf(stderr,"Expected: an identifier\n");
			break;
		case 6:
			fprintf(stderr,"Expected: \"\\n\"\n");
			break;
		case 7:
			fprintf(stderr,"Expected: \"cpu\" or \"\\n\"\n");
			break;
		case 8:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 9:
			fprintf(stderr,"Expected: \"\\n\"\n");
			break;
		case 10:
			fprintf(stderr,"Expected: \"b\"\n");
			break;
		case 11:
			if (item.type == SendOp) fprintf(stderr,"Expected: \"to\"\n");
			else if (item.type == RecvOp) fprintf(stderr,"Expected: \"from\"\n");
			else fprintf(stderr,"Expected: \"to\" or \"from\"\n");
			break;
		case 12:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 13:
			fprintf(stderr,"Expected: \"tag\", \"cpu\", \"nic\" or \"\\n\"\n");
			break;
		case 14:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 15:
			fprintf(stderr,"Expected: \"cpu\", \"nic\" or \"\\n\"\n");
			break;
		case 16:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 17:
			fprintf(stderr,"Expected: \"nic\" or \"\\n\"\n");
			break;
		case 18:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 19:
			fprintf(stderr,"Expected: \"\\n\"\n");
			break;
		case 20:
			fprintf(stderr,"Expected: an integer\n");
			break;
		case 21:
			fprintf(stderr,"Expected: \"{\"\n");
			break;
		case 22:
			fprintf(stderr,"Expected: an integer\n");
			break;
	}
	
	if (*(cursor-1) == '\n') {
		fprintf(stderr, "Instead the schedule contained: \"\\n\"\n");
	}
	else {
		fprintf(stderr, "Instead the schedule contained: \"%c\"\n", *(cursor-1));
	}


	
	exit(EXIT_FAILURE);

}
}

int main(int argc, char **argv){
    
	Scanner in;
	int lastprogress = 0;

	if (cmdline_parser(argc, argv, &args_info) != 0) {
		fprintf(stderr, "Couldn't parse command line arguments!\n");
		exit(EXIT_FAILURE);
	}

    memset((char*) &in, 0, sizeof(in));
   	in.fd = fopen(args_info.input_arg, "r");
	if (in.fd == NULL) {
		fprintf(stderr, "Couldn't open input file %s!\n", args_info.input_arg);
		exit(EXIT_FAILURE);
	}
	in.idtbl = new std::map<std::string, goalop_t>;
    
	uint32_t numranks = -1;

	while (true) {
		
		in.schedule = new Goal;
		
		scan(&in);

		if (in.num_ranks < 1) {
			fprintf(stderr, "Parse error: Number of Ranks undefined\n");
			exit(EXIT_FAILURE);
		}

		in.idtbl->clear();

		in.schedule->SetRank(in.curr_rank);
		in.schedule->SetNumRanks(in.num_ranks);
		in.schedule->SerializeSchedule(args_info.output_arg);
		delete in.schedule;
		int newprogress = round((((double) in.curr_rank) / in.num_ranks)*100);
		if (args_info.progress_given && (newprogress > lastprogress) ) {
			lastprogress = newprogress;
			printf("Progress %i%% - parsed schedule %i/%i\n", lastprogress, in.curr_rank, in.num_ranks);
		}
		if (in.curr_rank+1 == in.num_ranks) break;
	}
	
	free(in.bot);
	exit(EXIT_SUCCESS);
}
